### ISSUE TITLE
Array to string conversion error with Kirby 3.6 and PHP 8.0

### ISSUE THREAD

**Issue by davidjablonski** [thathoff/kirby-git-content#86] opened 2022-02-11 12:07 UTC
Hi there,

after updating to Kirby 3.6, I’ve been running into an **array to string conversion error** upon saving a page in the panel and thus creating a new commit. I've found [this issue](https://github.com/thathoff/kirby-git-content/issues/53) which may or may not be related, but for me, the error only appeared after updating to Kirby 3.6 and PHP 8.0 on my production server. Git logs tell me that the changes are not staged for commit. Manually committing and pushing to the repository works fine.

![Screenshot 2022-02-11 at 12 34 29](https://user-images.githubusercontent.com/9139357/153588156-239aa14a-b419-42e5-9e50-f8ebb57258d9.png)

Fixes I’ve tried:
- the error persists over multiple user accounts, all with a valid email and full name
- I’ve tried setting a custom (empty) commit message or adding a custom string for the author in src/KirbyGitHelper.php, but no luck

If anyone else has run into this errors or has any idea how to fix, I’d be very grateful. This plugin is proving incredibly helpful across a range of my projects, so I’d love to fix this soon. Thanks!

**Comment by thathoff** [comment] 2022-02-11 14:16
Can you try to open the browser’s console and check if you get a bit more information about this error? The file and line number where this happens would be great. You might need to enable debug mode.

Thank you!

**Comment by davidjablonski** [comment] 2022-02-21 11:55
I’ve done what you suggested, and it would [throw the same error as before](https://github.com/thathoff/kirby-git-content/issues/86#issuecomment-1036269602), pointing me to line 131 of `src/KirbyGitHelper.php`. I also threw an exception in line 131, which now points me to the `Console.php` file within the Git vendor library. Does that help?
![Screenshot 2022-02-21 at 12 51 17](https://user-images.githubusercontent.com/9139357/154950270-58bca8e0-5033-491e-9868-f45699c805b0.png)

**Comment by thathoff** [comment] 2022-02-21 12:28
That helps. Thank you. We’re also evaluating switching back to the original version of the git library we’re using (See #83), so this might be fixing it. But I’m still wondering whet the root cause of this error is.

**Comment by thathoff** [comment] 2022-08-10 06:31
This is fixed by switching to the new git library in v5.0.0

**Closed by thathoff** 2022-08-10 06:31 UTC
Labels: bug
