### ISSUE TITLE
Problems with Kirby 3.8.0-rc1 when installing without composer

### ISSUE THREAD

**Issue by chrfickinger** [thathoff/kirby-git-content#94] opened 2022-09-23 05:46 UTC
The plugin does not work since the latest update 3.8.0-rc.1 anymore.

Class "Kirby\Http\Request\Body" not found

see: https://github.com/getkirby/kirby/releases/tag/3.8.0-rc.1

**Comment by thathoff** [comment] 2022-09-24 11:33
Thanks for the bug report. I cannot reproduce it on our side with Kirby 3.8.0-rc.1 and version 5.0.1 of this plugin. Can you specify when exactly this error happens?

For me it looks more like an autoloader problem with your installation since the Kirby\Http\Request\Body has not changed in Kirby 3.8. and It’s not used anywhere in the plugin.

**Comment by thathoff** [comment] 2022-09-26 07:31
Can you please try to run `composer remove kirby` inside the ´site/plugins/kirby-git-content/kirby´ folder?

**Comment by thathoff** [comment] 2022-09-27 06:24
Oh, I’ve given you the wrong command. Please try `composer remove getkirby/cms`

**Comment by afbora** [comment] 2022-09-29 09:50
@chrfickinger I guess you're using the plugin in `/site/plugins` directory. Could you test following steps please?

1. Go to `/site/plugins/kirby-git-content` directory
2. Remove `"getkirby/cms": "^3.6.0",` line in `composer.json`
3. Run `composer update`  in `/site/plugins/kirby-git-content` directory
4. What do you get after these steps?

**Comment by thathoff** [comment] 2022-09-29 09:58
Thanks @afbora, that was exactly what I tried to accomplish with `composer remove getkirby/cms`.

I tried to reproduce this issue locally but even if I ran `composer install` inside the plugin’s dir everything worked well with 3.8.

**Comment by thathoff** [comment] 2022-09-29 10:09
So the idea is that the plugin requires at least Kirby 3.6.0. To support plugin installation without composer we would need to remove the "getkirby/cms": "^3.6.0" dependency form the plugin. But in this case composer would not enforce this Kirby version. Any Ideas how to solve this @afbora? :)

I just saw that some plugins set the `kirby-cms-path` option to false. But I think that would not solve the problem right?

**Comment by thathoff** [comment] 2022-09-29 10:09
@chrfickinger Great, what exactly solved the problem for you?

**Comment by afbora** [comment] 2022-09-29 10:20
Also works `"kirby-cms-path": false` for me.

````json
{
  "require": {
    "czproject/git-php": "^4.0.1",
    "getkirby/cms": "^3.8.0-rc.2",
    "getkirby/composer-installer": "^1.1"
  },
  "extra": {
    "installer-name": "git-content",
    "kirby-cms-path": false
  }
}
````

**Comment by thathoff** [comment] 2022-09-29 10:23
Yeah, but I would like to keep the dependency at `"getkirby/cms": "^3.6.0"`. Does that work for you too?

**Comment by afbora** [comment] 2022-09-29 10:28
@thathoff Unfortunately, no.

> Type of Kirby\Cms\Url::$home must be ?string (as in class Kirby\Http\Url)

**Comment by thathoff** [comment] 2022-09-29 10:36
Hmm, I think the issue is that `^3.6.0` installs the latest release version of Kirby and not the RC. So it’s an issue only if you run some RC versions of Kirby I think.

**Comment by afbora** [comment] 2022-09-29 10:40
@thathoff I think you're totally right 👍 When 3.8.0 stable version released, should work.

**Comment by thathoff** [comment] 2022-09-29 10:53
Thank you. I’ll close this issue for now.

**Closed by thathoff** 2022-09-29 10:53 UTC

**Comment by afbora** [comment] 2022-09-29 11:00
@thathoff Could you add `version` info for `composer.json` file to work stable for 3.8.0.

**Comment by thathoff** [comment] 2022-09-29 11:11
Sorry, what exactly do you mean with “ add version info for composer.json”? :)

**Comment by afbora** [comment] 2022-09-29 12:13
@thathoff https://github.com/thathoff/kirby-git-content/pull/95
